config/routes.rb
# == Route Map
#
#   Prefix Verb  URI Pattern          Controller#Action
#     root GET   /                    pages#welcome
#    users GET   /users(.:format)     users#index
#          POST  /users(.:format)     users#create
# new_user GET   /users/new(.:format) users#new
#     user PATCH /users/:id(.:format) users#update
#          PUT   /users/:id(.:format) users#update
#

Rails.application.routes.draw do

root :to => 'pages#welcome'

get '/users/edit' => 'users#edit'

get '/groups/search' => 'groups#search'
get '/groups/search_index' => 'groups#search_index'
get '/groups/:id/leave' => 'groups#leave_group', :as => 'group_leave'
get '/groups/:id/edit' => 'groups#edit', :as => 'group_edit'
get '/groups/:id/join' => 'groups#join', :as => 'group_join'
get '/groups/approve/:id' => 'groups#accept_member'
get '/groups/reject/:id' => 'groups#reject_member'
get '/groups/:id/admin/:user' => 'groups#make_admin'
get '/groups/:id/remove/:user' => 'groups#remove_user'

get '/events/:id/search/' => 'events#search'
get '/events/:id/delete' => 'events#destroy'
get '/events/:id/attending' => 'events#attending', :as => 'event_attending'
get '/events/:id/not_attending' => 'events#not_attending', :as => 'event_not_attending'
get '/events/rate/:id/:rated' => 'events#add_rating'

get '/details/:id/:imdbid' => 'events#details'
get '/details/:id/:imdbid/update_movie' => 'events#update_movie'

get '/readme' => 'pages#readme'

resources :users, :only  => [:new, :create, :index, :update, :show]
resources :groups, :only => [:new, :create, :index, :update, :show]
resources :events

get '/signup' => 'users#new'

get '/login' => 'session#new'
post '/login' => 'session#create'
delete '/login' => 'session#destroy'

end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id         :integer          not null, primary key
#  name       :text
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Group < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
  has_many :users
  has_many :events, :through => :users
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :authorise, :only => [:index]

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    # group_name = params[:name]
    req = Cloudinary::Uploader.upload( params[:group][:image] ) if params[:group][:image]
    @group = Group.create group_params
    if req
      @group.image = req["url"]
    end
    if @group.save
      @current_user.group_id = @group.id
      @current_user.group_admin = true
      @current_user.group_member = true
      @current_user.save
      redirect_to @group
    else
      render :new
    end

  end


  def show
    @group = Group.find params[:id]
    @events = Event.all.order('date DESC')
  end

  def edit
    @group = Group.find params[:id]
  end

  def update
    req = Cloudinary::Uploader.upload( params[:group][:image] )
    group = Group.find params[:id]
    group.image = req["url"]
    group.update group_params
    redirect_to group
  end

  def search
    @name = params[:name]
    @group_search = Group.where("name like ?", "%#{@name}%")
  end

  def search_index
  end

  def join
    @group = Group.find params[:id]
    @current_user.group_id = @group.id
    @current_user.group_member = false
    @current_user.save
    redirect_to @group
  end

  def accept_member
    user = User.find params[:id]
    user.group_member = true
    user.save
    redirect_to "/groups/#{@current_user.group_id}"
  end

  def reject_member
    user = User.find params[:id]
    user.group_member = nil
    user.save
    redirect_to "/groups/#{@current_user.group_id}"
  end

  def leave_group
    if @current_user.group_admin
      @current_user.group_admin = false
    end
    @current_user.group_member = false
    @current_user.group_id = nil
    @current_user.save
    redirect_to root_path
  end

  def remove_user
    user = User.find params[:user]
    group = Group.find params[:id]
    user.group_member = false
    user.group_id = nil
    user.save
    redirect_to group
  end

  def make_admin
    user = User.find params[:user]
    group = Group.find params[:id]
    user.group_admin = true
    user.save
    redirect_to group
  end

  private
  def group_params
    params.require(:group).permit(:name)
  end

  def authorise
    redirect_to root_path unless (@current_user.present? && @current_user.admin?)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group, :html => {:class => "rails_form"}) do |f| %>
  <fieldset>
    <%= f.label :name, 'Group Name' %>
    <%= f.text_field :name %>
</fieldset>

  <fieldset>
    <%= f.label :image, 'Group Photo' %>
    <span class="upload"><%= f.file_field :image %></span>
  </fieldset>
  <p>

  <label></label>  <span class="ruby_smallbutton"><%= f.submit %></span>
  </p>
<% end %>

app/views/groups/edit.html.erb
<h1>Edit Movie Night Group</h1>

<%= render :partial => 'form' %>

app/views/groups/index.html.erb
<h1>Groups index</h1>
<% @groups.each do |group| %>
<p><%= link_to group.name, group_path(group.id) %></p>
<% end %>

app/views/groups/new.html.erb
  <h1 class=>Create New Movie Night Group</h1>




    <%= render :partial => 'form' %>
    <div class="error_div">
        <% if @group.errors.any? %>
          <ul>
            <% @group.errors.full_messages.each do |message| %>
              <li><%= message %></li>

            <% end %>
          </ul>
      <% end %>
    </div>

app/views/groups/search.html.erb
<div class="over_container">
<h1 class="intro">Group Search</h1>
<div class="cinema_screen"><% @group_search.each do |group| %>
<p><%= link_to(group.name, group_path(group.id)) %></p>
<% end %>
</div>
</div>

app/views/groups/search_index.html.erb
<div class="over_container">
<h1 class="intro">Group Search</h1>
<% if @current_user.present? && @current_user.group_member != true %>
<div class="cinema_screen">
<h3>Search for a Group to Join</h3>
<p></p><p></p>
<form action="/groups/search/">
  <label class="search_form">Group name:</label>
  <input class="search_form" type="text" name="name">
  <input class="button_small" value="Search" type="submit">
</form>
<p></p><hr><p></p>
<p>Once you find the group you are looking for, the administrator of this group can approve your request to join this group.</p>
<% elsif @current_user.group_member == true %>
  <p>You are already a member of <%= @current_user.group.name %>. <%= link_to("Leave group?", group_leave_path) %></p>
<% end %>
</div>
</div>

app/views/groups/show.html.erb
<div class="flex_container">

  <div class="flex_left">

    <% if @group.image %>
    <%= image_tag(@group.image, :class => 'feature') %>
    <% end %>
    <% if @current_user.group_id != @group.id %>
    <p><%= link_to 'Request to Join', group_join_path, :class => "button" %></p>
    <% elsif @current_user.group_id == @group.id && @current_user.group_member == false %>
    <p>Your request to join this group is pending.</p>
    <% elsif @current_user.group_id == @group.id && @current_user.group_member == nil %>
    <p>Sorry, your request to join this group has been denied.</p>
    <% end %>

    <% if @current_user.group_id == @group.id && @current_user.group_member == true %>

    <h3>Group Members:</h3>
    <% @group.users.each do |user| %>
    <% if user.group_member == true %>
    <ul>
      <li><%= user.name_first %>
        <%= user.name_last %>
        <% if @current_user.group_admin && !user.group_admin %>
        (<%= link_to 'Make Admin', "/groups/#{@group.id}/admin/#{user.id}" %>)
         (<%= link_to 'Remove', "/groups/#{@group.id}/remove/#{user.id}" %>)
        <% end %>
      </li>
    </ul>
    <% end %>
    <% end %>


    <% if @current_user.present? && @current_user.group_admin? %>
    <h3>Membership Requests:</h3>
    <% @group.users.each do |user| %>
    <% if user.group_member == false %>
    <ul>
      <li><%= user.name_first %>
        <%= user.name_last %>
        (<%= link_to 'Approve', "/groups/approve/#{user.id}" %>
        /
        <%= link_to 'Reject', "/groups/reject/#{user.id}" %>)</li>
    </ul>
    <% end %>
    <% end %>
    <% end %>
    <% end %>
  </div>
  <div class="flex_right">
<% if @current_user.group_id == @group.id && @current_user.group_member == true %>
    <h3>Group Events:
    </h3>
    <div class="group_events">
      <% @events.each do |event| %>
      <% if @group.id == event.group_id %>
      <% @movie = HTTParty.get "http://omdbapi.com?i=#{event.imdb_id}" %>
      <ul>
        <li><%= @movie["Title"] %>
          at
          <%= link_to(event.location, event_path(event.id)) %>
          on
          <%= event.date.strftime '%A %e %B, %Y' %></li>
      </ul>
      <% end %>
      <% end %>

    </div>
    <% end %>
  </div>
</div>

<% if @current_user.group_id == @group.id && @current_user.group_member == true %>
<hr>
<div class="bottom_links">
  <%= link_to "  Create Event", new_event_path, :class => "button" %>
  <%= link_to "  Edit Group", group_edit_path, :class => "button" %>
  <% if @current_user.group_admin? && (@group.users.where(:group_admin => true).length < 2) %>
  <button class="button butt">Exit Group</button>
<% else %>
  <%= link_to "  Leave Group", group_leave_path, :class => "button" %>
  <% end %>
</div>

<div id="disqus_thread">
  <script>
    /**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/

    var disqus_config = function () {
      // this.page.url = PAGE_URL; // Replace PAGE_URL with your page's canonical URL variable
      this.page.identifier = <%= @group.id %>; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };

    (function () { // DON'T EDIT BELOW THIS LINE
      var d = document,
        s = d.createElement('script');

      s.src = '//movie-night.disqus.com/embed.js';

      s.setAttribute('data-timestamp', + new Date());
      (d.head || d.body).appendChild(s);
    })();
  </script>
  <noscript>Please enable JavaScript to view the
    <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a>
  </noscript>

</div>
<% end %>