config/routes.rb
# == Route Map
#
#   Prefix Verb  URI Pattern          Controller#Action
#     root GET   /                    pages#welcome
#    users GET   /users(.:format)     users#index
#          POST  /users(.:format)     users#create
# new_user GET   /users/new(.:format) users#new
#     user PATCH /users/:id(.:format) users#update
#          PUT   /users/:id(.:format) users#update
#

Rails.application.routes.draw do

root :to => 'pages#welcome'

get '/users/edit' => 'users#edit'

get '/groups/search' => 'groups#search'
get '/groups/search_index' => 'groups#search_index'
get '/groups/:id/leave' => 'groups#leave_group', :as => 'group_leave'
get '/groups/:id/edit' => 'groups#edit', :as => 'group_edit'
get '/groups/:id/join' => 'groups#join', :as => 'group_join'
get '/groups/approve/:id' => 'groups#accept_member'
get '/groups/reject/:id' => 'groups#reject_member'
get '/groups/:id/admin/:user' => 'groups#make_admin'
get '/groups/:id/remove/:user' => 'groups#remove_user'

get '/events/:id/search/' => 'events#search'
get '/events/:id/delete' => 'events#destroy'
get '/events/:id/attending' => 'events#attending', :as => 'event_attending'
get '/events/:id/not_attending' => 'events#not_attending', :as => 'event_not_attending'
get '/events/rate/:id/:rated' => 'events#add_rating'

get '/details/:id/:imdbid' => 'events#details'
get '/details/:id/:imdbid/update_movie' => 'events#update_movie'

get '/readme' => 'pages#readme'

resources :users, :only  => [:new, :create, :index, :update, :show]
resources :groups, :only => [:new, :create, :index, :update, :show]
resources :events

get '/signup' => 'users#new'

get '/login' => 'session#new'
post '/login' => 'session#create'
delete '/login' => 'session#destroy'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :text
#  name_first      :text
#  name_last       :text
#  password_digest :text
#  image           :text
#  admin           :boolean          default("false")
#  group_id        :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  group_admin     :boolean
#  group_member    :boolean
#

class User < ActiveRecord::Base
  has_secure_password
  validates :email, :presence => true, :uniqueness => true
  has_and_belongs_to_many :events
  belongs_to :group
  has_many :ratings
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorise, :only => [:index]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    req = Cloudinary::Uploader.upload( params[:user][:image] )
    @user = User.new user_params
    @user.image = req["url"]
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = @current_user
  end

  def show
    @user = User.find params[:id]
  end

  def update
    req = Cloudinary::Uploader.upload( params[:user][:image] ) if params[:user][:image]
    user = @current_user
    user.image = req["url"] if req
    user.update user_params
    redirect_to user_path
  end

  private
  def user_params
    params.require(:user).permit(:name_first, :name_last, :email, :password, :password_confirmation)
  end

  def authorise
    redirect_to root_path unless (@current_user.present? && @current_user.admin?)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= form_for(@user, :html => {:multipart => true, :class => "rails_form"}) do |f| %>
<fieldset>
<%= f.label :email %>
<%= f.email_field :email %>
</fieldset>
<fieldset>
<%= f.label :name_first, "First name" %>
<%= f.text_field :name_first %>
</fieldset>
<fieldset>
<%= f.label :name_last, "Last name" %>
<%= f.text_field :name_last %>
</fieldset>
<fieldset>
<%= f.label :password, "New Password" %>
<%= f.password_field :password %>
</fieldset>
<fieldset>
<%= f.label :password_confirmation, "New Password" %>
<%= f.password_field :password_confirmation %>
</fieldset>
<fieldset>
<%= f.label :image, 'Photo' %>
<span class="upload"><%= f.file_field :image %></span>
</fieldset>
<fieldset>
<span class="ruby_smallbutton"><%= f.submit %></span>
</fieldset>
<% end %>

app/views/users/index.html.erb
<h1>List of all Users.</h1>
<% @users.each do |user| %>
<p><%= user.name_first %> <%= link_to(user.name_last, user_path(user.id)) %> since <%= user.created_at %></p>
<% end %>

app/views/users/new.html.erb
<h1>Sign up to Movie Night</h1>

<% if @user.errors.any? %>
  <ol>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ol>
<% end %>

<%= form_for(@user, :html => {:class=> "rails_form"}) do |f| %>
<p><%= f.label :name_first, 'First name' %>
  <%= f.text_field :name_first, :required => true %></p>

  <p><%= f.label :name_last, 'Last name' %>
  <%= f.text_field :name_last %></p>

  <p><%= f.label :email %>
  <%= f.email_field :email, :required => true %></p>

  <p><%= f.label :password %>
  <%= f.password_field :password, :required => true %></p>

  <p><%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, :required => true %></p>

  <p><%= f.label :image, 'Photo' %>
  <span class="upload"><%= f.file_field :image %></p></span>

  <p><span class="ruby_smallbutton"><%= f.submit "Sign up" %></span>

<% end %>

app/views/users/show.html.erb
<h1><%= @user.name_first %> <%= @user.name_last %></h1>


<div class="flex_container">

<div class="flex_left">

<% if @current_user.group_member == true %>
<p>Member of: <%= link_to(@user.group.name, group_path(@user.group)) %></p>
<% end %>
<img class="profile_img" src="<%= @user.image %>" alt="<%= @user.name_first %> photo goes here">
</div>
<div class="flex_center">


<h3>Events Attended</h3>
<% @user.events.each do |event| %>
<ul>
  <li><%= link_to event.location, event %> - <%= event.date.strftime '%A %e %B, %Y' %></li>
</ul>
<% end %>
</div>

</div>
<hr>
<div class="bottom_links">
<p><%= link_to "Edit Profile", users_edit_path, :class => "button" %></p>
</div>