config/routes.rb
# == Route Map
#
#   Prefix Verb  URI Pattern          Controller#Action
#     root GET   /                    pages#welcome
#    users GET   /users(.:format)     users#index
#          POST  /users(.:format)     users#create
# new_user GET   /users/new(.:format) users#new
#     user PATCH /users/:id(.:format) users#update
#          PUT   /users/:id(.:format) users#update
#

Rails.application.routes.draw do

root :to => 'pages#welcome'

get '/users/edit' => 'users#edit'

get '/groups/search' => 'groups#search'
get '/groups/search_index' => 'groups#search_index'
get '/groups/:id/leave' => 'groups#leave_group', :as => 'group_leave'
get '/groups/:id/edit' => 'groups#edit', :as => 'group_edit'
get '/groups/:id/join' => 'groups#join', :as => 'group_join'
get '/groups/approve/:id' => 'groups#accept_member'
get '/groups/reject/:id' => 'groups#reject_member'
get '/groups/:id/admin/:user' => 'groups#make_admin'
get '/groups/:id/remove/:user' => 'groups#remove_user'

get '/events/:id/search/' => 'events#search'
get '/events/:id/delete' => 'events#destroy'
get '/events/:id/attending' => 'events#attending', :as => 'event_attending'
get '/events/:id/not_attending' => 'events#not_attending', :as => 'event_not_attending'
get '/events/rate/:id/:rated' => 'events#add_rating'

get '/details/:id/:imdbid' => 'events#details'
get '/details/:id/:imdbid/update_movie' => 'events#update_movie'

get '/readme' => 'pages#readme'

resources :users, :only  => [:new, :create, :index, :update, :show]
resources :groups, :only => [:new, :create, :index, :update, :show]
resources :events

get '/signup' => 'users#new'

get '/login' => 'session#new'
post '/login' => 'session#create'
delete '/login' => 'session#destroy'

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id         :integer          not null, primary key
#  location   :text
#  imdb_id    :text
#  date       :date
#  time       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  details    :text
#  group_id   :integer
#

class Event < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :ratings
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authorise, :only => [:index]

  def index
    @events = Event.all.order('date DESC')
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find params[:id]
  end

  def update
    event = Event.find params[:id]
    event.update event_params
    redirect_to event
  end

  def create
    event = Event.create event_params
    event.group_id = @current_user.group_id
    event.save
    redirect_to event
  end

  def show
    @event = Event.find params[:id]
    imdb = @event.imdb_id
    @movie = HTTParty.get "http://omdbapi.com?i=#{imdb}"
    @ratings = @event.ratings
  end

  def search
    title = params[:title]
    @event_id = params[:id]
    @result = HTTParty.get "http://omdbapi.com?s=#{title}"
  end

  def details
    imdb = params[:imdbid]
    @event_id = params[:id]
    @movie = HTTParty.get "http://omdbapi.com?i=#{imdb}"
  end

  def update_movie
    imdb_id = params[:imdbid]
    @event = Event.find params[:id]
    @event.imdb_id = imdb_id
    @event.save
    redirect_to event_path
  end

  def destroy
    event = Event.find params[:id]
    # @group = Group.find params[:eventid]
    event.destroy
    redirect_to group_path(event.group_id)
  end

  def attending
    event = Event.find params[:id]
    event.users << @current_user
    event.save
    redirect_to event
  end

  def not_attending
    event = Event.find params[:id]
    event.users.delete(@current_user)
    redirect_to event
  end

  def add_rating
    event = Event.find params[:id]
    rated = params[:rated]
    if @current_user.group_id != event.group_id
      redirect_to root_path
    else
      if event.ratings.exists?(user_id: @current_user.id)
        event.ratings.destroy(event.ratings.where(:user_id => @current_user.id))
      end
        rating = Rating.create
        rating.user_id = @current_user.id
        rating.rating_score = rated
        rating.event_id = params[:id]
        rating.save
        redirect_to event
    end
  end

  private
  def event_params
    params.require(:event).permit(:location, :date, :time, :details, :group_id)
  end

  def authorise
    redirect_to root_path unless (@current_user.present? && @current_user.admin?)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event, :html => {:class => "rails_form"}) do |f| %>
  <fieldset>
    <%= f.label :location %>
    <%= f.text_field :location, :required => 'true' %>
  </fieldset>

  <fieldset>
    <%= f.label :date %>
    <%= f.date_field :date, :required => 'true' %>
  </fieldset>

  <fieldset>
    <%= f.label :time %>
    <%= f.text_field :time %>
  </fieldset>

  <fieldset>
    <%= f.label :details %>
    <%= f.text_field :details %>
  </fieldset>

  <label></label> <span class="ruby_smallbutton"> <%= f.submit %></span>
<% end %>

app/views/events/details.html.erb
<h2><%= @movie["Title"] %> (<%= @movie["Year"] %>)</h2>
<p>Director: <%= @movie["Director"] %></p>
<p>Plot: <%= @movie["Plot"] %></p>
<img src="<%=@movie["Poster"] %>">

<p><a href="/details/<%= @event_id %>/<%= @movie["imdbID"]%>/update_movie">
   <button class="button">Select Movie</button>
</a></p>

app/views/events/edit.html.erb
<h1>Edit <%= @current_user.group.name %> Event</h1>

<%= render :partial => 'form' %>

app/views/events/index.html.erb
<h1>Events</h1>
<% @events.each do |event| %>
<p><%= link_to event.location, event_path(event.id) %> at <%= event.date.strftime '%A %e %B, %Y' %></p>
<% end %>

app/views/events/new.html.erb
<h1>Create <%= @current_user.group.name %> Event</h1>

<%= render :partial => 'form' %>

app/views/events/search.html.erb
<h1>Search Results</h1>
<h3>Your search results are below</h3>

<p>
  <% @result["Search"].each do |i| %>
  <p><%= image_tag i["Poster"], :class => "thumb" %><a href="/details/<%= @event_id %>/<%=@imdb = i["imdbID"]%>"><%= i["Title"] %></a></p>
  <% end %>
</p>

app/views/events/show.html.erb
<h1>Movie Night Event Details</h1>
<h2><%= @event.location %>
  on
  <%= @event.date.strftime '%A %e %B, %Y' %></h2>
<p><b>Details:</b>
  <%= @event.details %></p>
<hr>
<% if @event.imdb_id %>
<h3><%= @movie["Title"] %>
  (<%= @movie["Year"] %>)</h3>
<% end %>

<div class="flex_container">
  <% if @event.imdb_id %>
  <div class="flex_left">
    <p><%= image_tag @movie["Poster"] %></p>
  </div>
  <% end %>

<% if @event.imdb_id %>
  <div class="flex_center">

    <p>
      <b>Director:</b>
      <%= @movie["Director"] %></p>
    <p>
      <b>Starring:</b>
      <%= @movie["Actors"] %></p>
    <p>
      <b>Runtime:</b>
      <%= @movie["Runtime"] %></p>
    <p>
      <b>Genre:</b>
      <%= @movie["Genre"] %></p>
    <p>
      <b>IMDB Rating:</b>
      <%= @movie["imdbRating"] %></p>
    <p>
      <b>Plot:</b>
      <%= @movie["Plot"] %></p>

  </div>
<% end %>
  <div class="flex_right">
    <h3>Attendees</h3>
    <% @event.users.each do |user| %>
    <% rating = Rating.find_by({ event_id: @event.id, user_id: user.id }) %>

    <div class="attendee"><%= user.name_first %>
      <% if rating %></div>
    <div class="emoji_div"><%= image_tag "#{rating.rating_score }.png", :class => "emoji" %>
      <% end %></div>
  </p>
  <br>
  <% end %>

  <% if @event.users.where(:id => @current_user.id).any? %>
  <p><%= link_to 'Not Attending', event_not_attending_path, :class => "button" %></p>
  <h6>You are attending.</h6>
<% else %>
  <p><%= link_to 'Attending', event_attending_path, :class => "button" %></p>
  <h6>You are not attending.</h6>
  <% end %>
</div>
</div>
<% if @event.imdb_id %>
  <p>Rate the choice of film:
    <%= link_to image_tag(("heart.png"), :class => 'emoji hvr-bounce-in'), "/events/rate/#{@event.id}/heart" %>
    <%= link_to image_tag(("smiley.png"), :class => 'emoji hvr-bounce-in'), "/events/rate/#{@event.id}/smiley" %>
    <%= link_to image_tag(("neutral.png"), :class => 'emoji hvr-bounce-in'), "/events/rate/#{@event.id}/neutral" %>
    <%= link_to image_tag(("unamused.png"), :class => 'emoji hvr-bounce-in'), "/events/rate/#{@event.id}/unamused" %>
    <%= link_to image_tag(("poo.png"), :class => 'emoji hvr-bounce-in'), "/events/rate/#{@event.id}/poo" %>
  </p>
<% end %>
  <form class="event_film" action="/events/<%= @event.id %>/search">
    <label>Add or change film: </label>
    <input type="text" name="title">
    <input type="submit" value="Search" class="button_small">
  </form>

<hr>
<div class="bottom_links">
<%= link_to 'Edit Event', edit_event_path(@event), :class => "button" %>
<% if @current_user.group_admin %>
<%= link_to 'Delete Event', @event, :method => :delete, :class => "button" %>
<% end %>
</div>