config/routes.rb
# == Route Map
#
#   Prefix Verb  URI Pattern          Controller#Action
#     root GET   /                    pages#welcome
#    users GET   /users(.:format)     users#index
#          POST  /users(.:format)     users#create
# new_user GET   /users/new(.:format) users#new
#     user PATCH /users/:id(.:format) users#update
#          PUT   /users/:id(.:format) users#update
#

Rails.application.routes.draw do

root :to => 'pages#welcome'

get '/users/edit' => 'users#edit'

get '/groups/search' => 'groups#search'
get '/groups/search_index' => 'groups#search_index'
get '/groups/:id/leave' => 'groups#leave_group', :as => 'group_leave'
get '/groups/:id/edit' => 'groups#edit', :as => 'group_edit'
get '/groups/:id/join' => 'groups#join', :as => 'group_join'
get '/groups/approve/:id' => 'groups#accept_member'
get '/groups/reject/:id' => 'groups#reject_member'
get '/groups/:id/admin/:user' => 'groups#make_admin'
get '/groups/:id/remove/:user' => 'groups#remove_user'

get '/events/:id/search/' => 'events#search'
get '/events/:id/delete' => 'events#destroy'
get '/events/:id/attending' => 'events#attending', :as => 'event_attending'
get '/events/:id/not_attending' => 'events#not_attending', :as => 'event_not_attending'
get '/events/rate/:id/:rated' => 'events#add_rating'

get '/details/:id/:imdbid' => 'events#details'
get '/details/:id/:imdbid/update_movie' => 'events#update_movie'

get '/readme' => 'pages#readme'

resources :users, :only  => [:new, :create, :index, :update, :show]
resources :groups, :only => [:new, :create, :index, :update, :show]
resources :events

get '/signup' => 'users#new'

get '/login' => 'session#new'
post '/login' => 'session#create'
delete '/login' => 'session#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movienight</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= cloudinary_js_config %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="top_nav">
      <div class="title">
        <a href="/">
          <h4>Movie</h4>
          <h5>night</h5><span class="beta">beta</span>
        </a>
      </div>
      <div class="user_buttons">
        <% if @current_user.present? %>
        <%= link_to @current_user.name_first, user_path(@current_user) %>
        <%= link_to "Logout", login_path, :method => :delete %>
        <%= link_to (cl_image_tag @current_user.image, :class => "thumb person_thumb hvr-bob"), user_path(@current_user) %>
      <% else %>
        <%= link_to 'Sign up', signup_path %>
        <%= link_to 'Login', login_path %>
        <% end %>
      </div>
    </div>

    <div class="container">
<% if @current_user.present? %>
      <nav>
        <% if @current_user.present? %>
        <% if @current_user.admin? %>
        <%= link_to "All Users", users_path %>
        <%= link_to "All Groups", groups_path %>
        <%= link_to 'All Events', events_path %>
        <% end %>
        <% if @current_user.group_id == nil%>
        <%= link_to "Create Group", new_group_path %>
        <%= link_to "Join Group", '/groups/search_index' %>
      <% else %>
        <h3><%= link_to @current_user.group.name, group_path(@current_user.group_id) %></h3>
        <% end %>
        <% end %>
      </nav>
<% end %>
      <div class="yield_container">
        <%= yield %>
      </div>
    </div>
    <footer>
      Copyright 2016 | Ian Lenehan | <%= link_to "Read Me", readme_path %>
    </footer>
  </body>
</html>